version: "3.3"
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    hostname: mongo
    volumes:
      - mongo_data:/mongodata
    ports:
      - 27017:27017
    networks:
      - mongobi-bridge
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      - mongobi-bridge
    depends_on:
      - mongo
  mongobi:
    build: .
    image: mongobi:latest
    restart: always
    volumes:
      - ./config/mongosqld.conf:/home/mongobi/mongosqld.conf
      - mongobi_logs:/logs
    container_name: mongobi
    hostname: mongobi
    ports:
      - 3307:3307
    networks:
      - mongobi-bridge
    depends_on:
      - mongo

volumes:
  mongo_data: {}
  mongobi_logs: {}

networks:
  mongobi-bridge:
    driver: bridge